### ISSUE TITLE
Instantiating Plyr, Acquiring Instance

### ISSUE THREAD

**Issue by martindale** [Selz/plyr#118]
There's little documentation about acquiring a Plyr instance, despite all the documentation describing a simple `player` variable.  How is this `player` element acquired?  `document.getElementById`?  Why is Plyr seemingly auto-binding to certain elements, but not others?  How can I specifically target an element for Plyr instantiation?

**Comment by martindale** [comment]
Suggestion: `var player = plyr.setup('.some-css-selector');`

**Comment by SamPotts** [comment]
Well the instance is stored against the original selector. I agree it could be made more clear but it's essentially covered here:
https://github.com/Selz/plyr#api

e.g. 

```javascript
var player = document.querySelectorAll(".player")[0].plyr;
```

Also setup will return the element similar to your second example, however if you have multiple on the page, it will return them all, which might be less than useful. 

```javascript
var player = plyr.setup(config);
```

However currently setup only accepts a full config as an argument, I could easily change `setup()` to allow either the config, the selector or the config and selector if you think that's easier to understand? 

```javascript
var player = plyr.setup('.js-player');
var player = plyr.setup('.js-player', config);
var player = plyr.setup(config);
```

**Comment by calvintam236** [comment]
In my opinion, I would prefer:
```
var player = plyr.setup('.js-player');
var player = plyr.setup('.js-player', config);
var player = plyr.setup(config);
```

**Comment by SamPotts** [comment]
What do you think @martindale ?

**Comment by SamPotts** [comment]
OK. I've made it like so:

Passing a [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList):
```javascript
plyr.setup(document.querySelectorAll('.js-player'), options);
```

Passing a [HTMLElement](https://developer.mozilla.org/en/docs/Web/API/HTMLElement):
```javascript
plyr.setup(document.querySelector('.js-player'), options);
```

Passing a [string selector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll):
```javascript
plyr.setup('.js-player', options);
```

Passing just the options object:
```javascript
plyr.setup(options);
```

This will go in v1.4 in the next couple of days

**Comment by SamPotts** [comment]
Added docs here in the `develop` branch:
https://github.com/selz/plyr/tree/develop#quick-setup
and 
https://github.com/selz/plyr/tree/develop#api

Will add more on the 

**Warning** classnames and the default hook will change in 1.4 to `plyr` instead of `player` to be consistent. Easy enough to find/replace.

**Comment by martindale** [comment]
I like the new method, it's much more in line with expectations.  I'd go so far as to not instantiate unless _explicitly_ called; that is to say, don't automatically instantiate on anything (well, definitely not a class name).  Barring that, it looks good! :+1:

Ah, and the other requirement of having a nested `<video>` or `<audio>` tag -- just let it bind to anything, and automatically create the required child elements.

**Comment by SamPotts** [comment]
Yeah, you're probably right. I guess my thinking was just to make it easier for the less technically advanced users out there. I agree with you though, it'd be better to not do it automatically. 

My issue with not having an initial `<audio>` and `<video>` element on the page is that there's no non JS fallback in place then. I've tried to keep this a progressive enhancement thing.

**Comment by SamPotts** [comment]
Fixed in [v1.5.0](https://github.com/Selz/plyr/releases/tag/v1.5.0)

**Comment by apudiu** [comment]
Unfortunately I'm still not clear how to get current instance? 
My setup is
`const players = Plyr.setup('.plyr', options)`

in this page I've 10 video now how do I can get current object/instance? so I can do something using their events...

**Comment by sampotts** [comment]
Why did you give all my replies thumbs down? I'd have replied to help but don't want to risk another thumbs down! Good luck with it.

**Comment by apudiu** [comment]
@sampotts sorry for that. Actually it's doesn't clarify how to get an instance or current (playing) instance. Like in many videos (in a page) how do you get the instance(s) that's are actually playing?

Btw... I managed to get it in a very different way, & its working fine. I also added feature (on my app only):
1. Stop other player (thats are playing) as soon as last one starts to play.
2. Play only one player at a time, if one already playing then stop that & start new one.
3. Pop out the player (like fb) when user scrolls down.
4. Resizing & moving of the poped player..

btw thanks for your effort.

**Comment by jahid32** [comment]
@apudiu Can you please tell the procedure how to get the current instance

**Comment by apudiu** [comment]
sure @jahid32, I passed an additional property in the config (in this case an ID) then I initialized all player in a variable `players`. while initializing I added several event handlers (like, end, playing, paused etc..) to all player. whenever any instance starts playing I can check the id of that (my passed id) instance then I can do anything with it. you also can loop the `players` & check existing getters to check which one is playing.
