### ISSUE TITLE
plyr.js:376 Uncaught TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by sanserna** [Selz/plyr#186]
I'm Using plyr to embed a video from youtube but when I initialize using `plyr.setup();` always get the same error, I want the player to show the controls, I already load the svg file as the documentation says, but the error is blocking the controls visibility, how can i fix de error?????

**Comment by SamPotts** [comment]
Fixed in the latest build. Thanks for reporting :+1:

**Comment by magicspon** [comment]
I'm still getting this error, but only when I use the source method.

```
var player = plyr.setup('.js-media-player', {
		controls: [
			'play'
		],
		html: controlsHtml
	})[0];

	player.source({
	  type:       'video',
	  title:      'Example title',
	  sources: [{
	      src:    '143418951',
	      type:   'vimeo'
	  }]
	});
```

html 

```
<div class="plyr js-media-player">
     <div></div>
</div>
```
